In [1]:
import pandas as pd

In [58]:
pisa = pd.read_csv('pisa2009train.csv')

#### How many students are there in the training set?

In [3]:
pisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3663 entries, 0 to 3662
Data columns (total 24 columns):
grade                    3663 non-null int64
male                     3663 non-null int64
raceeth                  3628 non-null object
preschool                3607 non-null float64
expectBachelors          3601 non-null float64
motherHS                 3566 non-null float64
motherBachelors          3266 non-null float64
motherWork               3570 non-null float64
fatherHS                 3418 non-null float64
fatherBachelors          3094 non-null float64
fatherWork               3430 non-null float64
selfBornUS               3594 non-null float64
motherBornUS             3592 non-null float64
fatherBornUS             3550 non-null float64
englishAtHome            3592 non-null float64
computerForSchoolwork    3598 non-null float64
read30MinsADay           3629 non-null float64
minutesPerWeekEnglish    3477 non-null float64
studentsInEnglish        3414 non-null float64
schoolHasLibrary         3520 non-null float64
publicSchool             3663 non-null int64
urban                    3663 non-null int64
schoolSize               3501 non-null float64
readingScore             3663 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 686.9+ KB

#### 2. What is the average reading test score of males and females?

In [5]:
#pd.crosstab(index=pisa['readingScore'], columns=pisa['male'], margins=True)

In [3]:
readingScoreMales = pisa[pisa['male'] == 1]

In [4]:
readingScoreMales['readingScore'].describe()

count    1872.000000
mean      483.532479
std        97.907065
min       202.790000
25%       414.390000
50%       482.340000
75%       555.930000
max       740.470000
Name: readingScore, dtype: float64

In [5]:
readingScoreFemales = pisa[pisa['male'] == 0]
readingScoreFemales['readingScore'].describe()

count    1791.000000
mean      512.940631
std        90.567258
min       168.550000
25%       449.215000
50%       513.160000
75%       577.150000
max       746.000000
Name: readingScore, dtype: float64

#### 3. Which variables are missing data in at least one observation in the training set?

In [11]:
pisa.isnull().any()

grade                    False
male                     False
raceeth                   True
preschool                 True
expectBachelors           True
motherHS                  True
motherBachelors           True
motherWork                True
fatherHS                  True
fatherBachelors           True
fatherWork                True
selfBornUS                True
motherBornUS              True
fatherBornUS              True
englishAtHome             True
computerForSchoolwork     True
read30MinsADay            True
minutesPerWeekEnglish     True
studentsInEnglish         True
schoolHasLibrary          True
publicSchool             False
urban                    False
schoolSize                True
readingScore             False
dtype: bool

#### Linear regression discards observations with missing data, so let's remove all such observations from the training and testing sets.

#### 4. How many observations are now in the training set?

#### 5. How many observations are now in the testing set?

In [59]:
pisaWithoutMissingValues = pisa.dropna(axis = 0)

In [60]:
pisaWithoutMissingValues.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2414 entries, 1 to 3662
Data columns (total 24 columns):
grade                    2414 non-null int64
male                     2414 non-null int64
raceeth                  2414 non-null object
preschool                2414 non-null float64
expectBachelors          2414 non-null float64
motherHS                 2414 non-null float64
motherBachelors          2414 non-null float64
motherWork               2414 non-null float64
fatherHS                 2414 non-null float64
fatherBachelors          2414 non-null float64
fatherWork               2414 non-null float64
selfBornUS               2414 non-null float64
motherBornUS             2414 non-null float64
fatherBornUS             2414 non-null float64
englishAtHome            2414 non-null float64
computerForSchoolwork    2414 non-null float64
read30MinsADay           2414 non-null float64
minutesPerWeekEnglish    2414 non-null float64
studentsInEnglish        2414 non-null float64
schoolHasLibrary         2414 non-null float64
publicSchool             2414 non-null int64
urban                    2414 non-null int64
schoolSize               2414 non-null float64
readingScore             2414 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 471.5+ KB

In [8]:
pisaTest = pd.read_csv('pisa2009test.csv')

In [9]:
pisaTestWithoutMissingValues = pisaTest.dropna(axis = 0)

In [24]:
pisaTestWithoutMissingValues.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 990 entries, 0 to 1569
Data columns (total 24 columns):
grade                    990 non-null int64
male                     990 non-null int64
raceeth                  990 non-null object
preschool                990 non-null float64
expectBachelors          990 non-null float64
motherHS                 990 non-null float64
motherBachelors          990 non-null float64
motherWork               990 non-null float64
fatherHS                 990 non-null float64
fatherBachelors          990 non-null float64
fatherWork               990 non-null float64
selfBornUS               990 non-null float64
motherBornUS             990 non-null float64
fatherBornUS             990 non-null float64
englishAtHome            990 non-null float64
computerForSchoolwork    990 non-null float64
read30MinsADay           990 non-null float64
minutesPerWeekEnglish    990 non-null float64
studentsInEnglish        990 non-null float64
schoolHasLibrary         990 non-null float64
publicSchool             990 non-null int64
urban                    990 non-null int64
schoolSize               990 non-null float64
readingScore             990 non-null float64
dtypes: float64(19), int64(4), object(1)
memory usage: 193.4+ KB

#### Factor variables are variables that take on a discrete set of values, like the "Region" variable. This is an unordered factor because there isn't any natural ordering between the levels. An ordered factor has a natural ordering between the levels (an example would be the classifications "large," "medium," and "small").

#### 6. Which of the following variables is an unordered factor with at least 3 levels?

- grade
- male
- raceeth

raceeth

#### 7. Which of the following variables is an ordered factor with at least 3 levels?
- grade
- male
- raceeth

grade

#### Male only has 2 levels (1 and 0). There is no natural ordering between the different values of raceeth, so it is an unordered factor. Meanwhile, we can order grades (8, 9, 10, 11, 12), so it is an ordered factor.

***

#### To include unordered factors in a linear regression model, we define one level as the "reference level" and add a binary variable for each of the remaining levels. In this way, a factor with n levels is replaced by n-1 binary variables. The reference level is typically selected to be the most frequently occurring level in the dataset.

#### As an example, consider the unordered factor variable "color", with levels "red", "green", and "blue". If "green" were the reference level, then we would add binary variables "colorred" and "colorblue" to a linear regression problem. All red examples would have colorred=1 and colorblue=0. All blue examples would have colorred=0 and colorblue=1. All green examples would have colorred=0 and colorblue=0.

#### Now, consider the variable "raceeth" in our problem, which has levels "American Indian/Alaska Native", "Asian", "Black", "Hispanic", "More than one race", "Native Hawaiian/Other Pacific Islander", and "White". Because it is the most common in our population, we will select White as the reference level.

#### Which binary variables will be included in the regression model?

- raceethAmerican Indian/Alaska Native
- raceethAsian
- raceethBlack
- raceethHispanic
- raceethMore than one race
- raceethNative Hawaiian/Other Pacific Islander
- raceethWhite

#### We create a binary variable for each level except the reference level, so we would create all these variables except for raceethWhite.

***

#### Consider again adding our unordered factor race to the regression model with reference level "White".

#### For a student who is Asian, which binary variables would be set to 0? All remaining variables will be set to 1.

- raceethAmerican Indian/Alaska Native
- raceethAsian
- raceethBlack
- raceethHispanic
- raceethMore than one race
- raceethNative Hawaiian/Other Pacific Islander

#### Everything except raceethAsian because it's value would be 1.

***

#### For a student who is white, which binary variables would be set to 0? All remaining variables will be set to 1.

- raceethAmerican Indian/Alaska Native
- raceethAsian
- raceethBlack
- raceethHispanic
- raceethMore than one race
- raceethNative Hawaiian/Other Pacific Islander

#### All of them. An Asian student will have raceethAsian set to 1 and all other raceeth binary variables set to 0. Because "White" is the reference level, a white student will have all raceeth binary variables set to 0.

***

#### What is the Multiple R-squared value of lmScore on the training set?

In [25]:
pisa.dtypes

grade                      int64
male                       int64
raceeth                   object
preschool                float64
expectBachelors          float64
motherHS                 float64
motherBachelors          float64
motherWork               float64
fatherHS                 float64
fatherBachelors          float64
fatherWork               float64
selfBornUS               float64
motherBornUS             float64
fatherBornUS             float64
englishAtHome            float64
computerForSchoolwork    float64
read30MinsADay           float64
minutesPerWeekEnglish    float64
studentsInEnglish        float64
schoolHasLibrary         float64
publicSchool               int64
urban                      int64
schoolSize               float64
readingScore             float64
dtype: object

#### Resources:

- https://stackoverflow.com/questions/38954525/how-to-have-catagorical-factor-variables-in-python
- https://medium.com/swlh/super-simple-machine-learning-simple-linear-regression-part-3-validation-65b8c11fa36b

In [61]:
pisaWithoutMissingValues.head()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,selfBornUS,motherBornUS,fatherBornUS,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore
1,11,1,White,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,450.0,25.0,1.0,1,0,1173.0,575.01
3,10,0,Black,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,200.0,23.0,1.0,1,1,2640.0,458.11
4,10,1,Hispanic,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,250.0,35.0,1.0,1,1,1095.0,613.89
7,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,300.0,30.0,1.0,1,0,1913.0,439.36
9,10,1,More than one race,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,294.0,24.0,1.0,1,0,899.0,465.90

In [19]:
pd.options.display.max_columns = None
pisaWithoutMissingValues.head()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,selfBornUS,motherBornUS,fatherBornUS,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore
1,11,1,White,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,450.0,25.0,1.0,1,0,1173.0,575.01
3,10,0,Black,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,200.0,23.0,1.0,1,1,2640.0,458.11
4,10,1,Hispanic,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,250.0,35.0,1.0,1,1,1095.0,613.89
7,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,300.0,30.0,1.0,1,0,1913.0,439.36
9,10,1,More than one race,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,294.0,24.0,1.0,1,0,899.0,465.90

#### The variables below have been converted into categorical variables. Their datatype is 'float64'.

In [62]:
categorical_columns = ['male', 'preschool', 'expectBachelors', 'motherHS', 'motherBachelors', 'motherWork', 'fatherHS', 
                      'fatherBachelors', 'fatherWork','selfBornUS', 'motherBornUS', 'fatherBornUS', 'englishAtHome', 
                      'computerForSchoolwork', 'read30MinsADay', 'schoolHasLibrary', 'publicSchool','urban']

In [63]:
for columns in categorical_columns:
    pisaWithoutMissingValues[columns] = pisaWithoutMissingValues[columns].astype('category')

C:\Users\Vivek\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [64]:
pisaWithoutMissingValues.dtypes

grade                       int64
male                     category
raceeth                    object
preschool                category
expectBachelors          category
motherHS                 category
motherBachelors          category
motherWork               category
fatherHS                 category
fatherBachelors          category
fatherWork               category
selfBornUS               category
motherBornUS             category
fatherBornUS             category
englishAtHome            category
computerForSchoolwork    category
read30MinsADay           category
minutesPerWeekEnglish     float64
studentsInEnglish         float64
schoolHasLibrary         category
publicSchool             category
urban                    category
schoolSize                float64
readingScore              float64
dtype: object

#### Variable 'raceeth' is of type 'object'. It has to be converted into a dummy variable. Note that is has labels such as 'White', 'Hispanic', etc., so in order to use it in Regression model, we have to convert it into a dummy variable. The other categorical columns have values 0 and 1. So it's not an issue whereas this one has 'text' or 'labels'. That's why we have to do this.

In [65]:
categorical_raceeth = pd.get_dummies(pisaWithoutMissingValues['raceeth'])
pisaWithoutMissingValues = pd.concat([pisaWithoutMissingValues, categorical_raceeth], axis=1)
#pisaWithoutMissingValues.drop()
pisaWithoutMissingValues.tail()

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,selfBornUS,motherBornUS,fatherBornUS,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore,American Indian/Alaska Native,Asian,Black,Hispanic,More than one race,Native Hawaiian/Other Pacific Islander,White
3655,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,245.0,20.0,1.0,1,0,149.0,604.76,0,0,0,0,0,0,1
3657,10,1,More than one race,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,270.0,24.0,1.0,1,0,1471.0,492.76,0,0,0,0,1,0,0
3659,9,1,White,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,450.0,16.0,1.0,1,0,1317.0,444.90,0,0,0,0,0,0,1
3660,10,1,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,16.0,1.0,1,1,539.0,476.89,0,0,0,1,0,0,0
3662,10,0,White,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,235.0,25.0,1.0,1,0,227.0,551.85,0,0,0,0,0,0,1

#### Note that we don't have to have all the columns. We should have n-1 columns if there are n labels. Since the values in the remaining columns are all 0, it means that the value is 'White' in this case. We are going to use 'White' as the reference level.
#### Here we see that some more columns have been added to the DataFrame - American Indian/Alaska Native, Asian, Black, Hispanic, More than one race, Native Hawaiian/Other Pacific Islander, White. We are going to drop 'White' as it's not necessary.

In [24]:
#pisaWithoutMissingValues.drop(['White'], axis=1)

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,selfBornUS,motherBornUS,fatherBornUS,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore,American Indian/Alaska Native,Asian,Black,Hispanic,More than one race,Native Hawaiian/Other Pacific Islander
1,11,1,White,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,450.0,25.0,1.0,1,0,1173.0,575.01,0,0,0,0,0,0
3,10,0,Black,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,200.0,23.0,1.0,1,1,2640.0,458.11,0,0,1,0,0,0
4,10,1,Hispanic,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,250.0,35.0,1.0,1,1,1095.0,613.89,0,0,0,1,0,0
7,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,300.0,30.0,1.0,1,0,1913.0,439.36,0,0,0,0,0,0
9,10,1,More than one race,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,294.0,24.0,1.0,1,0,899.0,465.90,0,0,0,0,1,0
11,10,0,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,232.0,14.0,1.0,1,0,1733.0,508.95,0,0,0,1,0,0
13,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,225.0,20.0,1.0,1,0,149.0,646.38,0,0,0,0,0,0
14,10,0,Hispanic,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,270.0,25.0,1.0,1,1,1400.0,403.77,0,0,0,1,0,0
15,11,1,White,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,275.0,30.0,1.0,1,1,1988.0,423.73,0,0,0,0,0,0
16,9,1,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,15.0,1.0,0,1,915.0,646.60,0,0,0,0,0,0
17,11,0,White,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,250.0,20.0,1.0,1,0,636.0,532.86,0,0,0,0,0,0
18,10,0,White,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,250.0,12.0,1.0,1,0,854.0,547.32,0,0,0,0,0,0
19,10,1,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,315.0,40.0,1.0,1,1,2999.0,569.32,0,0,0,0,0,0
21,10,1,White,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,30.0,1.0,1,0,2748.0,563.55,0,0,0,0,0,0
22,9,0,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,235.0,32.0,1.0,1,0,149.0,493.38,0,0,0,0,0,0
23,10,0,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,600.0,30.0,1.0,1,0,361.0,472.41,0,0,0,1,0,0
24,10,0,White,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,240.0,26.0,1.0,0,1,575.0,513.72,0,0,0,0,0,0
25,11,1,Black,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1296.0,30.0,1.0,1,1,3261.0,577.90,0,0,1,0,0,0
26,10,1,White,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,300.0,30.0,1.0,1,0,2340.0,555.85,0,0,0,0,0,0
27,10,1,White,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,250.0,25.0,1.0,1,0,1913.0,649.65,0,0,0,0,0,0
31,10,1,White,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,90.0,20.0,1.0,1,0,2569.0,596.41,0,0,0,0,0,0
33,9,1,White,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,180.0,25.0,1.0,0,1,1212.0,561.94,0,0,0,0,0,0
34,11,0,White,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,250.0,25.0,1.0,1,0,509.0,637.65,0,0,0,0,0,0
36,10,1,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,315.0,25.0,1.0,1,0,899.0,488.43,0,0,0,1,0,0
37,10,0,Black,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,270.0,25.0,1.0,1,0,1526.0,490.68,0,0,1,0,0,0
38,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,225.0,25.0,1.0,1,0,276.0,591.57,0,0,0,0,0,0
40,10,0,Hispanic,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,225.0,30.0,1.0,1,0,1250.0,444.29,0,0,0,1,0,0
42,10,0,White,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,250.0,30.0,1.0,1,0,2878.0,639.55,0,0,0,0,0,0
44,10,0,White,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,225.0,25.0,1.0,1,0,276.0,453.90,0,0,0,0,0,0
45,11,1,White,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,290.0,12.0,1.0,1,0,929.0,566.75,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3617,10,0,Hispanic,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,900.0,15.0,1.0,1,1,1062.0,477.18,0,0,0,1,0,0
3618,10,1,White,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,30.0,1.0,0,0,1064.0,569.80,0,0,0,0,0,0
3619,10,0,Black,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,200.0,28.0,1.0,1,0,846.0,380.58,0,0,1,0,0,0
3620,10,1,White,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,55.0,18.0,1.0,1,0,362.0,506.55,0,0,0,0,0,0
3621,9,1,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,250.0,25.0,1.0,1,0,1064.0,425.90,0,0,0,0,0,0
3622,11,1,White,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,30.0,1.0,1,0,854.0,588.72,0,0,0,0,0,0
3623,10,0,White,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,261.0,30.0,1.0,1,1,1734.0,445.40,0,0,0,0,0,0
3624,10,0,More than one race,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,50.0,25.0,1.0,1,0,505.0,458.11,0,0,0,0,1,0
3625,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,40.0,20.0,1.0,1,0,1387.0,467.09,0,0,0,0,0,0
3627,10,0,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,195.0,29.0,1.0,1,1,2999.0,582.75,0,0,0,1,0,0
3628,10,1,White,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,410.0,30.0,1.0,1,0,930.0,418.60,0,0,0,0,0,0
3630,11,1,Hispanic,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,280.0,36.0,1.0,1,1,3164.0,336.35,0,0,0,1,0,0
3631,10,0,White,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,270.0,14.0,1.0,1,0,389.0,634.79,0,0,0,0,0,0
3632,10,0,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,195.0,25.0,1.0,1,1,2640.0,660.13,0,0,0,0,0,0
3635,10,1,White,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,235.0,15.0,1.0,0,1,356.0,396.00,0,0,0,0,0,0
3637,10,0,White,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,20.0,1.0,1,0,1327.0,488.22,0,0,0,0,0,0
3639,10,1,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,275.0,12.0,1.0,1,1,539.0,539.17,0,0,0,1,0,0
3640,11,0,White,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,200.0,30.0,1.0,1,0,1680.0,401.71,0,0,0,0,0,0
3642,10,0,White,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,220.0,30.0,1.0,1,0,754.0,523.49,0,0,0,0,0,0
3644,10,1,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,250.0,13.0,1.0,1,0,754.0,543.66,0,0,0,0,0,0
3645,10,1,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,200.0,20.0,1.0,1,0,846.0,464.70,0,0,0,0,0,0
3647,10,1,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,325.0,25.0,1.0,1,0,3004.0,574.77,0,0,0,1,0,0
3649,10,1,Hispanic,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,225.0,30.0,1.0,1,1,1110.0,444.74,0,0,0,1,0,0
3653,11,0,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,275.0,20.0,0.0,1,1,502.0,530.64,0,0,0,0,0,0
3654,10,1,White,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,350.0,30.0,1.0,1,0,1101.0,442.25,0,0,0,0,0,0
3655,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,245.0,20.0,1.0,1,0,149.0,604.76,0,0,0,0,0,0
3657,10,1,More than one race,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,270.0,24.0,1.0,1,0,1471.0,492.76,0,0,0,0,1,0
3659,9,1,White,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,450.0,16.0,1.0,1,0,1317.0,444.90,0,0,0,0,0,0
3660,10,1,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,225.0,16.0,1.0,1,1,539.0,476.89,0,0,0,1,0,0
3662,10,0,White,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,235.0,25.0,1.0,1,0,227.0,551.85,0,0,0,0,0,0

In [66]:
from sklearn import linear_model

In [67]:
linearRegression = linear_model.LinearRegression()

In [28]:
#pisaTrainWithoutMissingValues = pisa.dropna(axis = 0)

In [29]:
# pisaTrainWithoutMissingValues['raceeth'] = pisaTrainWithoutMissingValues['raceeth'].astype('category')

C:\Users\Vivek\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
#pisaTrainWithoutMissingValues.dtypes

grade                       int64
male                        int64
raceeth                  category
preschool                 float64
expectBachelors           float64
motherHS                  float64
motherBachelors           float64
motherWork                float64
fatherHS                  float64
fatherBachelors           float64
fatherWork                float64
selfBornUS                float64
motherBornUS              float64
fatherBornUS              float64
englishAtHome             float64
computerForSchoolwork     float64
read30MinsADay            float64
minutesPerWeekEnglish     float64
studentsInEnglish         float64
schoolHasLibrary          float64
publicSchool                int64
urban                       int64
schoolSize                float64
readingScore              float64
dtype: object

In [68]:
pisaWithoutMissingValues.dtypes

grade                                        int64
male                                      category
raceeth                                     object
preschool                                 category
expectBachelors                           category
motherHS                                  category
motherBachelors                           category
motherWork                                category
fatherHS                                  category
fatherBachelors                           category
fatherWork                                category
selfBornUS                                category
motherBornUS                              category
fatherBornUS                              category
englishAtHome                             category
computerForSchoolwork                     category
read30MinsADay                            category
minutesPerWeekEnglish                      float64
studentsInEnglish                          float64
schoolHasLibrary                          category
publicSchool                              category
urban                                     category
schoolSize                                 float64
readingScore                               float64
American Indian/Alaska Native                uint8
Asian                                        uint8
Black                                        uint8
Hispanic                                     uint8
More than one race                           uint8
Native Hawaiian/Other Pacific Islander       uint8
White                                        uint8
dtype: object

In [69]:
X_train = pisaWithoutMissingValues[['grade','male', 'preschool', 'expectBachelors', 'motherHS', 'motherBachelors', 'motherWork', 'fatherHS', 
                      'fatherBachelors', 'fatherWork','selfBornUS', 'motherBornUS', 'fatherBornUS', 'englishAtHome', 
                      'computerForSchoolwork', 'read30MinsADay', 'schoolHasLibrary', 'publicSchool','urban', 
                  'minutesPerWeekEnglish', 'studentsInEnglish', 'schoolSize', 'American Indian/Alaska Native', 'Asian', 'Black',
              'Hispanic', 'More than one race', 'Native Hawaiian/Other Pacific Islander', 'White']]
y_train = pisaWithoutMissingValues[['readingScore']]

In [70]:
linearRegression.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [75]:
linearRegression.residues_
#12993364.9

C:\Users\Vivek\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:70: DeprecationWarning: Function residues_ is deprecated; ``residues_`` is deprecated and will be removed in 0.19
  warnings.warn(msg, category=DeprecationWarning)

array([], dtype=float64)

In [72]:
linearRegression.intercept_

array([ 115.28067518])

In [73]:
linearRegression.coef_

array([[  2.95427071e+01,  -1.45216535e+01,  -4.46367032e+00,
          5.52670801e+01,   6.05877432e+00,   1.26380678e+01,
         -2.80910060e+00,   4.01821353e+00,   1.69297547e+01,
          5.84279834e+00,  -3.80627792e+00,  -8.79815308e+00,
          4.30699432e+00,   8.03568537e+00,   2.25002323e+01,
          3.48719242e+01,   1.22150850e+01,  -1.68574750e+01,
         -1.10131762e-01,   1.27884515e-02,  -2.86630774e-01,
          6.54038148e-03,  -3.87916689e+01,   2.43753331e+01,
         -3.85266888e+01,  -1.04898273e+01,   1.15631362e+01,
          2.33840574e+01,   2.84856583e+01]])

***

#### What is the training-set root-mean squared error (RMSE)?

In [74]:
linearRegression.score(X_train, y_train)

0.32514335592135679

#### R^2 = 0.325

In [76]:
import math

In [78]:
RMSE = math.sqrt((12993364.9/len(pisaWithoutMissingValues)))
RMSE

73.36555118771378

***

#### Consider two students A and B. They have all variable values the same, except that student A is in grade 11 and student B is in grade 9. What is the predicted reading score of student A minus the predicted reading score of student B?

59.09

#### The coefficient 29.54 on grade is the difference in reading score between two students who are identical other than having a difference in grade of 1. Because A and B have a difference in grade of 2, the model predicts that student A has a reading score that is 2*29.54 larger.

***

#### What is the meaning of the coefficient associated with variable raceethAsian?

- Predicted average reading score of an Asian student
- Difference between the average reading score of an Asian student and the average reading score of a white student
- Difference between the average reading score of an Asian student and the average reading score of all the students in the dataset
- Predicted difference in the reading score between an Asian student and a white student who is otherwise identical

*Predicted difference in the reading score between an Asian student and a white student who is otherwise identical*

#### The only difference between an Asian student and white student with otherwise identical variables is that the former has raceethAsian=1 and the latter has raceethAsian=0. The predicted reading score for these two students will differ by the coefficient on the variable raceethAsian.

***

#### https://stackoverflow.com/questions/33833832/building-multi-regression-model-throws-error-pandas-data-cast-to-numpy-dtype-o

#### Based on the significance codes, which variables are candidates for removal from the model?

#### We can see which variables were significant at the 0.05 level.

***

#### What is the range between the maximum and minimum predicted reading score on the test set?

In [86]:

for columns in categorical_columns:
    pisaTestWithoutMissingValues[columns] = pisaTestWithoutMissingValues[columns].astype('category')


categorical_raceeth = pd.get_dummies(pisaTestWithoutMissingValues['raceeth'])

pisaTestWithoutMissingValues = pd.concat([pisaTestWithoutMissingValues, categorical_raceeth], axis=1)
#pisaWithoutMissingValues.drop()
pisaTestWithoutMissingValues.tail()

C:\Users\Vivek\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,grade,male,raceeth,preschool,expectBachelors,motherHS,motherBachelors,motherWork,fatherHS,fatherBachelors,fatherWork,selfBornUS,motherBornUS,fatherBornUS,englishAtHome,computerForSchoolwork,read30MinsADay,minutesPerWeekEnglish,studentsInEnglish,schoolHasLibrary,publicSchool,urban,schoolSize,readingScore,American Indian/Alaska Native,Asian,Black,Hispanic,More than one race,Native Hawaiian/Other Pacific Islander,White
1562,10,0,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,270.0,25.0,1.0,1,1,2999.0,667.20,0,0,0,0,0,0,1
1563,10,0,Hispanic,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,270.0,28.0,1.0,1,1,2999.0,541.76,0,0,0,1,0,0,0
1565,9,1,White,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,300.0,20.0,1.0,1,0,987.0,465.58,0,0,0,0,0,0,1
1568,10,0,White,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,450.0,20.0,1.0,1,0,987.0,596.34,0,0,0,0,0,0,1
1569,10,0,White,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,450.0,20.0,1.0,1,0,987.0,577.43,0,0,0,0,0,0,1

In [87]:
X_test = pisaTestWithoutMissingValues[['grade','male', 'preschool', 'expectBachelors', 'motherHS', 'motherBachelors', 'motherWork', 'fatherHS', 
                      'fatherBachelors', 'fatherWork','selfBornUS', 'motherBornUS', 'fatherBornUS', 'englishAtHome', 
                      'computerForSchoolwork', 'read30MinsADay', 'schoolHasLibrary', 'publicSchool','urban', 
                  'minutesPerWeekEnglish', 'studentsInEnglish', 'schoolSize', 'American Indian/Alaska Native', 'Asian', 'Black',
              'Hispanic', 'More than one race', 'Native Hawaiian/Other Pacific Islander', 'White']]
y_test = pisaTestWithoutMissingValues[['readingScore']]

In [90]:
predTest = linearRegression.predict(X_test)
linearRegression

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [93]:
import numpy as np
np.min(predTest)

353.22312311396217

In [94]:
np.max(predTest)

637.69143490910369

In [95]:
637.69143 - 353.22312

284.46831

***

In [100]:
linearRegression.residues_

C:\Users\Vivek\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:70: DeprecationWarning: Function residues_ is deprecated; ``residues_`` is deprecated and will be removed in 0.19
  warnings.warn(msg, category=DeprecationWarning)

array([], dtype=float64)

#### What is the root-mean squared error (RMSE) on the testing set?

In [107]:
from sklearn.metrics import mean_squared_error, r2_score

In [108]:
print("Mean squared error")
mse = mean_squared_error(y_test, predTest)
mse

Mean squared error

5820.2852233782132

In [110]:
print("Root mean squared error")
rmse = math.sqrt(mse)
rmse

Root mean squared error

76.29079383109219

#### What is the test-set R-squared value?

In [99]:
r2_score(y_test, predTest)

0.26115545096875792

#### What is the predicted test score used in the baseline model? Remember to compute this value using the training set and not the test set.

In [116]:
baseline = np.mean(pisaTrainWithoutMissingValues['readingScore'])
print("Baseline ", baseline)

Baseline  517.9628873239429

#### What is the sum of squared errors of the baseline model on the testing set? HINT: We call the sum of squared errors for the baseline model the total sum of squares (SST).

In [119]:
SST = np.sum((baseline - pisaTestWithoutMissingValues['readingScore']) ** 2)
print("SST is ", SST)

SST is  7802354.077613839

In [128]:
SSE = np.sum((predTest - pisaTestWithoutMissingValues['readingScore'].values) ** 2)
print("SSE is ", SSE)
##This doesn't look right.

SSE is  10381521577.7